blank_issues_enabled: true
contact_links:
  - name: Questions & Discussions
    url: https://github.com/Indemnity83/always-bring-a-gift/discussions
    about: Ask questions and discuss ideas with the community
